version: "3.7"
services:
  mysqlDB:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "trackdota"
    volumes:
      - trackdota_mysql:/var/lib/mysql
  frontend:
    image: trackdota/frontend:latest
    container_name: trackdota_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  backend:
    image: trackdota/backend:latest
    container_name: trackdota_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqlDB
    ports:
      - "4000:5000"
volumes:
  trackdota_mysql:
